name: Release version

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Define docker image metadata
        uses: docker/metadata-action@v3
        id: metadata
        with:
          images: olegstepura/glibc-envsubst
          tags: |
            type=semver,pattern={{version}}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push an image to DockerHub
        uses: int128/kaniko-action@v1
        with:
          push: true
          file: Dockerfile
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}